apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki
    helm:
      values: | 
        service:
          name: loki
          type: LoadBalancer
    repoURL: https://grafana.github.io/loki/charts/
    targetRevision: 2.1.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
